version: "3"

services:

  spark-master:
    image: danielrodriguez/distributed-spark-proof
    command: bin/spark-class org.apache.spark.deploy.master.Master -h spark-master
    hostname: spark-master
    environment:
      MASTER: spark://spark-master:7077
      SPARK_CONF_DIR: /conf/master
      SPARK_PUBLIC_DNS: localhost
    expose:
      - 7001
      - 7002
      - 7003
      - 7004
      - 7005
      - 7006
      - 7077
      - 6066
    ports:
      - 4040:4040
      - 6066:6066
      - 7077:7077
      - 8080:8080
    deploy:
      placement:
        constraints: [danir2.machine.role==manager]
    networks:
      thesisnet:
        aliases:
          - spark-master

  spark-worker:
    image: danielrodriguez/distributed-spark-proof
    command: bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077
    hostname: spark-worker
    environment:
      SPARK_CONF_DIR: /conf/worker
      SPARK_WORKER_CORES: 2
      SPARK_WORKER_MEMORY: 4g
      SPARK_WORKER_PORT: 8881
      SPARK_WORKER_WEBUI_PORT: 8081
      SPARK_PUBLIC_DNS: localhost
    depends_on:
      - spark-master
    expose:
      - 7012
      - 7013
      - 7014
      - 7015
      - 7016
      - 8881
    deploy:
      mode: replicated
      replicas: 3
      placement:
        constraints: [danir2.machine.role==worker]
      restart_policy:
        condition: on-failure
    networks:
      thesisnet:

networks:
  thesisnet:
    driver: overlay